### ISSUE TITLE
Add *.pdf to .gitignore

### ISSUE THREAD

**Issue by Oedipsos** [jmoeil/PHYS-F302#1]
À chaque modification de la source, le document PDF généré est modifié, ce qui fait à chaque fois un fichier à commit en plus... Est-ce que l'ignorer ne serait pas une solution, en sachant que en général, le résultat de compilation n'est pas inclus dans la source qui l'a généré... On pourrait alors établir un système de versionning où on fait la realease du pdf, quand une section est considérée finie. 

Pour les contributeur.trice.s, cela ne pose aucun souci puisqu'iels ont de quoi compiler le document. Tt pour les autres, cela ne change rien non plus puisqu'un pdf pourri ne les intéressera pas non plus :D

**Comment by jmoeil** [comment]
On fait ça!

**Comment by Oedipsos** [comment]
Done in #2
